use std::fs::{OpenOptions, File};
use std::io::{Write, Read};
use std::env;
use colored::*;

fn main() {
    let home = env::var("HOME").expect("❌ تعذر العثور على مسار HOME");
    let alias_path = format!("{}/.bash_aliases", home);
    let bashrc_path = format!("{}/.bashrc", home);

    println!("{}", "🦁 Bakir-Linux Alias System v1.0".bold().bright_cyan());
    println!("{}", "-----------------------------------".bright_magenta());

    // قائمة الاختصارات السيادية
    let aliases = vec![
        ("update", "sudo apt update"),
        ("upgrade", "sudo apt upgrade"),
        ("install", "sudo apt install"),
        ("reboot", "sudo reboot"),
        ("cls", "clear"),
        ("proj", "cd ~/Bakir-Project"),
        ("lab", "cd ~/Bakir-Lab"), // إضافة اختصار للمختبر
        ("myip", "hostname -I"),
        ("reload", "source ~/.bashrc && source ~/.bash_aliases"),
        ("..", "cd .. text"),
        ("...", "cd ../.."),
    ];

    // 1. إنشاء أو تصفير ملف .bash_aliases
    let mut file = File::create(&alias_path).expect("❌ فشل إنشاء ملف الاختصارات");
    writeln!(file, "# --- BAKIR LINUX SOVEREIGN ALIASES ---").unwrap();
    writeln!(file, "# Generated by Bakir-Alias (Rust Tool)\n").unwrap();

    for (name, cmd) in aliases {
        writeln!(file, "alias {}='{}'", name, cmd).unwrap();
        println!("{} {} {} '{}'", "[+]".green(), "تم تسجيل الاختصار:".white(), name.bold().yellow(), cmd.cyan());
    }

    // 2. التحقق من الربط في .bashrc
    ensure_link(&bashrc_path);

    println!("{}", "\n✨ تمت العملية بنجاح! أغلق الترمنال وافتحه أو اكتب 'reload'.".bold().green());
}

fn ensure_link(path: &str) {
    let mut content = String::new();
    if let Ok(mut file) = File::open(path) {
        let _ = file.read_to_string(&mut content);
    }

    if !content.contains(".bash_aliases") {
        let link_code = "\n# Bakir-Linux Alias Link\nif [ -f ~/.bash_aliases ]; then\n    . ~/.bash_aliases\nfi\n";
        let mut file = OpenOptions::new().append(true).open(path).expect("❌ فشل الوصول لملف .bashrc");
        writeln!(file, "{}", link_code).expect("❌ فشل الكتابة في .bashrc");
        println!("\n{}", "🔗 تم ربط الملف بـ .bashrc بنجاح.".bright_blue());
    } else {
        println!("\n{}", "ℹ️ الملف مرتبط مسبقاً بـ .bashrc".bright_black());
    }
}
